# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/EditUser.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(670, 522)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(240, 470, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 631, 441))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.miBox = QtGui.QLineEdit(self.tab)
        self.miBox.setGeometry(QtCore.QRect(520, 90, 61, 31))
        self.miBox.setObjectName(_fromUtf8("miBox"))
        self.lNameBox = QtGui.QLineEdit(self.tab)
        self.lNameBox.setGeometry(QtCore.QRect(100, 90, 201, 31))
        self.lNameBox.setObjectName(_fromUtf8("lNameBox"))
        self.nLabel = QtGui.QLabel(self.tab)
        self.nLabel.setGeometry(QtCore.QRect(30, 96, 68, 21))
        self.nLabel.setObjectName(_fromUtf8("nLabel"))
        self.removeEmail = QtGui.QPushButton(self.tab)
        self.removeEmail.setGeometry(QtCore.QRect(320, 220, 31, 31))
        self.removeEmail.setObjectName(_fromUtf8("removeEmail"))
        self.uLabel2 = QtGui.QLabel(self.tab)
        self.uLabel2.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.uLabel2.setObjectName(_fromUtf8("uLabel2"))
        self.pLabel2 = QtGui.QLabel(self.tab)
        self.pLabel2.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.pLabel2.setObjectName(_fromUtf8("pLabel2"))
        self.phoneNumbers = QtGui.QListWidget(self.tab)
        self.phoneNumbers.setGeometry(QtCore.QRect(50, 190, 256, 192))
        self.phoneNumbers.setObjectName(_fromUtf8("phoneNumbers"))
        self.pnLabel = QtGui.QLabel(self.tab)
        self.pnLabel.setGeometry(QtCore.QRect(60, 160, 131, 21))
        self.pnLabel.setObjectName(_fromUtf8("pnLabel"))
        self.emailAdds = QtGui.QListWidget(self.tab)
        self.emailAdds.setGeometry(QtCore.QRect(360, 190, 256, 192))
        self.emailAdds.setObjectName(_fromUtf8("emailAdds"))
        self.createUserBox = QtGui.QLineEdit(self.tab)
        self.createUserBox.setGeometry(QtCore.QRect(100, 10, 201, 27))
        self.createUserBox.setObjectName(_fromUtf8("createUserBox"))
        self.addPhoneNumber = QtGui.QPushButton(self.tab)
        self.addPhoneNumber.setGeometry(QtCore.QRect(10, 190, 31, 31))
        self.addPhoneNumber.setObjectName(_fromUtf8("addPhoneNumber"))
        self.fNameBox = QtGui.QLineEdit(self.tab)
        self.fNameBox.setGeometry(QtCore.QRect(310, 90, 201, 31))
        self.fNameBox.setObjectName(_fromUtf8("fNameBox"))
        self.emaiLabel = QtGui.QLabel(self.tab)
        self.emaiLabel.setGeometry(QtCore.QRect(370, 160, 68, 21))
        self.emaiLabel.setObjectName(_fromUtf8("emaiLabel"))
        self.createPassBox = QtGui.QLineEdit(self.tab)
        self.createPassBox.setGeometry(QtCore.QRect(100, 40, 201, 27))
        self.createPassBox.setObjectName(_fromUtf8("createPassBox"))
        self.removePhoneNumber = QtGui.QPushButton(self.tab)
        self.removePhoneNumber.setGeometry(QtCore.QRect(10, 220, 31, 31))
        self.removePhoneNumber.setObjectName(_fromUtf8("removePhoneNumber"))
        self.addEmail = QtGui.QPushButton(self.tab)
        self.addEmail.setGeometry(QtCore.QRect(320, 190, 31, 31))
        self.addEmail.setObjectName(_fromUtf8("addEmail"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.addSkill = QtGui.QPushButton(self.widget)
        self.addSkill.setGeometry(QtCore.QRect(150, 40, 31, 31))
        self.addSkill.setObjectName(_fromUtf8("addSkill"))
        self.ageLabel = QtGui.QLabel(self.widget)
        self.ageLabel.setGeometry(QtCore.QRect(20, 16, 68, 31))
        self.ageLabel.setObjectName(_fromUtf8("ageLabel"))
        self.skillList = QtGui.QListWidget(self.widget)
        self.skillList.setGeometry(QtCore.QRect(190, 40, 421, 91))
        self.skillList.setObjectName(_fromUtf8("skillList"))
        self.skillLabel = QtGui.QLabel(self.widget)
        self.skillLabel.setGeometry(QtCore.QRect(200, 10, 131, 21))
        self.skillLabel.setObjectName(_fromUtf8("skillLabel"))
        self.spinBox = QtGui.QSpinBox(self.widget)
        self.spinBox.setGeometry(QtCore.QRect(60, 20, 61, 27))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.removeSkill = QtGui.QPushButton(self.widget)
        self.removeSkill.setGeometry(QtCore.QRect(150, 70, 31, 31))
        self.removeSkill.setObjectName(_fromUtf8("removeSkill"))
        self.addEduc = QtGui.QPushButton(self.widget)
        self.addEduc.setGeometry(QtCore.QRect(150, 300, 31, 31))
        self.addEduc.setObjectName(_fromUtf8("addEduc"))
        self.removeAddress = QtGui.QPushButton(self.widget)
        self.removeAddress.setGeometry(QtCore.QRect(150, 190, 31, 31))
        self.removeAddress.setObjectName(_fromUtf8("removeAddress"))
        self.addressList = QtGui.QListWidget(self.widget)
        self.addressList.setGeometry(QtCore.QRect(190, 160, 421, 91))
        self.addressList.setObjectName(_fromUtf8("addressList"))
        self.removeEduc = QtGui.QPushButton(self.widget)
        self.removeEduc.setGeometry(QtCore.QRect(150, 330, 31, 31))
        self.removeEduc.setObjectName(_fromUtf8("removeEduc"))
        self.addAddress = QtGui.QPushButton(self.widget)
        self.addAddress.setGeometry(QtCore.QRect(150, 160, 31, 31))
        self.addAddress.setObjectName(_fromUtf8("addA   ddress"))
        self.educList = QtGui.QListWidget(self.widget)
        self.educList.setGeometry(QtCore.QRect(190, 300, 421, 91))
        self.educList.setObjectName(_fromUtf8("educList"))
        self.addressLabel = QtGui.QLabel(self.widget)
        self.addressLabel.setGeometry(QtCore.QRect(200, 130, 131, 21))
        self.addressLabel.setObjectName(_fromUtf8("addressLabel"))
        self.educLabel = QtGui.QLabel(self.widget)
        self.educLabel.setGeometry(QtCore.QRect(190, 270, 181, 21))
        self.educLabel.setObjectName(_fromUtf8("educLabel"))
        self.tabWidget.addTab(self.widget, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.editPriv = QtGui.QCheckBox(self.tab_3)
        self.editPriv.setGeometry(QtCore.QRect(50, 250, 161, 21))
        self.editPriv.setObjectName(_fromUtf8("editPriv"))
        self.addPriv = QtGui.QCheckBox(self.tab_3)
        self.addPriv.setGeometry(QtCore.QRect(50, 220, 151, 21))
        self.addPriv.setObjectName(_fromUtf8("addPriv"))
        self.privLabel = QtGui.QLabel(self.tab_3)
        self.privLabel.setGeometry(QtCore.QRect(20, 190, 68, 17))
        self.privLabel.setObjectName(_fromUtf8("privLabel"))
        self.compLabel = QtGui.QLabel(self.tab_3)
        self.compLabel.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.compLabel.setObjectName(_fromUtf8("compLabel"))
        self.delPriv = QtGui.QCheckBox(self.tab_3)
        self.delPriv.setGeometry(QtCore.QRect(50, 280, 141, 21))
        self.delPriv.setObjectName(_fromUtf8("delPriv"))
        self.companyList = QtGui.QComboBox(self.tab_3)
        self.companyList.setGeometry(QtCore.QRect(30, 50, 281, 31))
        self.companyList.setObjectName(_fromUtf8("companyList"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tabWidget.raise_()
        self.buttonBox.raise_()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Edit Account", None))
        self.miBox.setPlaceholderText(_translate("Dialog", "M.I.", None))
        self.lNameBox.setPlaceholderText(_translate("Dialog", "Last name", None))
        self.nLabel.setText(_translate("Dialog", "Name:", None))
        self.removeEmail.setText(_translate("Dialog", "-", None))
        self.uLabel2.setText(_translate("Dialog", "Username:", None))
        self.pLabel2.setText(_translate("Dialog", "Password:", None))
        self.pnLabel.setText(_translate("Dialog", "Phone Numbers", None))
        self.addPhoneNumber.setText(_translate("Dialog", "+", None))
        self.fNameBox.setPlaceholderText(_translate("Dialog", "First name", None))
        self.emaiLabel.setText(_translate("Dialog", "Email", None))
        self.removePhoneNumber.setText(_translate("Dialog", "-", None))
        self.addEmail.setText(_translate("Dialog", "+", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "General Information", None))
        self.addSkill.setText(_translate("Dialog", "+", None))
        self.ageLabel.setText(_translate("Dialog", "Age:", None))
        self.skillLabel.setText(_translate("Dialog", "Skillset", None))
        self.removeSkill.setText(_translate("Dialog", "-", None))
        self.addEduc.setText(_translate("Dialog", "+", None))
        self.removeAddress.setText(_translate("Dialog", "-", None))
        self.removeEduc.setText(_translate("Dialog", "-", None))
        self.addAddress.setText(_translate("Dialog", "+", None))
        self.addressLabel.setText(_translate("Dialog", "Address", None))
        self.educLabel.setText(_translate("Dialog", "Educational Attainment", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Dialog", "Job Seeker Information", None))
        self.editPriv.setText(_translate("Dialog", "Edit Job Posts", None))
        self.addPriv.setText(_translate("Dialog", "Add Job Posts", None))
        self.privLabel.setText(_translate("Dialog", "Privileges", None))
        self.compLabel.setText(_translate("Dialog", "Company", None))
        self.delPriv.setText(_translate("Dialog", "Delete Job Posts", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Company Representative Information", None))

